version: "3.9"
services:
  db:
    image: postgis/postgis:12-3.1
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672"
      - "5672"
  app:
    build: .
    depends_on:
      - db
      - rabbitmq
