version: "3.9"
services:
  db:
    image: postgres:11.1-alpine
    ports:
      - "5432"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672"
      - "5672"
  app:
    build: .
    depends_on:
      - db
      - rabbitmq
